import XCTest
@testable import AgentsHUDCore

/// Cross-validates the Swift port against golden.json, which is generated by
/// running the ORIGINAL Node implementation over the same synthetic
/// transcripts (scripts/gen-golden.mjs). Any divergence in token math is a
/// porting bug, not a fixture problem.
final class GoldenWireTests: XCTestCase {
    struct Golden: Decodable {
        struct GSession: Decodable {
            var id: String
            var provider: String
            var cwd: String
            var project: String
            var model: String
            var lastActivity: Double
            var firstActivity: Double
            var usage: GUsage
            var contextTokens: Int
        }
        struct GUsage: Decodable {
            var input: Int
            var output: Int
            var cacheCreate: Int
            var cacheRead: Int
            var total: Int
        }
        struct GEvent: Decodable {
            var ts: Double
            var tokens: Int
        }
        struct GToday: Decodable {
            var tokens: Int
            var cacheWriteTokens: Int
            var costUSD: Double
        }
        var now: Double
        var sessions: [GSession]
        var usageEvents: [GEvent]
        var usage5h: Usage5h
        var today: GToday
    }

    /// Sessions whose timestamps come from file mtime (zeroed in the golden).
    private let timeless: Set<String> = ["s3"]

    private func fixturesURL() throws -> URL {
        let url = Bundle.module.resourceURL?.appendingPathComponent("Fixtures")
        return try XCTUnwrap(url)
    }

    private func loadGolden() throws -> Golden {
        let url = try fixturesURL().appendingPathComponent("golden.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Golden.self, from: data)
    }

    private func makeConfig() throws -> Config {
        let claudeHome = try fixturesURL().appendingPathComponent("claude-home")
        return Config(claudeDir: claudeHome.path)
    }

    func testProviderSessionsMatchNode() async throws {
        let golden = try loadGolden()
        let provider = ClaudeProvider(cfg: try makeConfig())
        let snap = await provider.collect()

        let sessions = snap.sessions.sorted { $0.id < $1.id }
        XCTAssertEqual(sessions.map(\.id), golden.sessions.map(\.id))

        for (got, want) in zip(sessions, golden.sessions) {
            XCTAssertEqual(got.provider, want.provider, want.id)
            XCTAssertEqual(got.cwd, want.cwd, want.id)
            XCTAssertEqual(got.project, want.project, want.id)
            XCTAssertEqual(got.model, want.model, want.id)
            XCTAssertEqual(got.usage.input, want.usage.input, want.id)
            XCTAssertEqual(got.usage.output, want.usage.output, want.id)
            XCTAssertEqual(got.usage.cacheCreate, want.usage.cacheCreate, want.id)
            XCTAssertEqual(got.usage.cacheRead, want.usage.cacheRead, want.id)
            XCTAssertEqual(got.usage.total, want.usage.total, want.id)
            XCTAssertEqual(got.contextTokens, want.contextTokens, want.id)
            if !timeless.contains(want.id) {
                XCTAssertEqual(got.lastActivity, want.lastActivity, want.id)
                XCTAssertEqual(got.firstActivity, want.firstActivity, want.id)
            }
        }
    }

    func testUsageEventsMatchNode() async throws {
        let golden = try loadGolden()
        let provider = ClaudeProvider(cfg: try makeConfig())
        let snap = await provider.collect()
        let events = snap.usageEvents.sorted { ($0.ts, $0.tokens) < ($1.ts, $1.tokens) }
        XCTAssertEqual(events.count, golden.usageEvents.count)
        for (got, want) in zip(events, golden.usageEvents) {
            XCTAssertEqual(got.ts, want.ts)
            XCTAssertEqual(got.tokens, want.tokens)
        }
    }

    func testUsage5hMatchesNode() async throws {
        let golden = try loadGolden()
        let provider = ClaudeProvider(cfg: try makeConfig())
        let snap = await provider.collect()
        let got = Usage5hCalculator.compute(events: snap.usageEvents, cfg: try makeConfig(), now: golden.now)
        XCTAssertEqual(got.percent, golden.usage5h.percent)
        XCTAssertEqual(got.tokensUsed, golden.usage5h.tokensUsed)
        XCTAssertEqual(got.tokenBudget, golden.usage5h.tokenBudget)
        XCTAssertEqual(got.resetInMinutes, golden.usage5h.resetInMinutes)
        XCTAssertEqual(got.blockStart, golden.usage5h.blockStart)
        XCTAssertEqual(got.blockEnd, golden.usage5h.blockEnd)
        XCTAssertEqual(got.burnRatePerMin, golden.usage5h.burnRatePerMin)
        XCTAssertEqual(got.source, golden.usage5h.source)
    }

    func testTodayUsageMatchesNode() throws {
        let golden = try loadGolden()
        // The golden is generated with TZ=Asia/Shanghai (see gen-golden.mjs).
        let tz = try XCTUnwrap(TimeZone(identifier: "Asia/Shanghai"))
        let got = TodayUsageScanner.compute(cfg: try makeConfig(), now: golden.now, timeZone: tz)
        XCTAssertEqual(got.tokens, golden.today.tokens)
        XCTAssertEqual(got.cacheWriteTokens, golden.today.cacheWriteTokens)
        XCTAssertEqual(got.costUSD, golden.today.costUSD, accuracy: 1e-9)
    }
}
